Repository RavidRo/service_anywhere, pull requests merged in 2022-06, with the labels that each got.

#158 Review dashboard
  api.ts
  dashboard/__tests__/connectViewModelTests.ts
  dashboard/__tests__/notificationsTests.ts
  dashboard/__tests__/ordersViewModelsTests.ts
  dashboard/__tests__/waitersViewModelsTests.ts
  dashboard/src/model/ordersModel.ts
  dashboard/src/network/api.ts
  dashboard/src/network/config.json
  dashboard/src/network/notifications.ts
  dashboard/src/typeGuard.ts
  dashboard/src/view/ReviewView.tsx
  dashboard/src/view/loginView.tsx
  dashboard/src/viewController/ConnectViewController.tsx
  dashboard/src/viewController/OrdersViewController.tsx
  dashboard/src/viewController/StatusViewController.tsx
  dashboard/src/viewController/WaiterViewController.tsx
  dashboard/src/viewController/reviewViewController.tsx
  dashboard/src/viewModel/connectViewModel.ts
  dashboard/src/viewModel/ordersViewModel.ts
  dashboard/src/viewModel/waitersViewModel.ts
Labels: enhancement

#170 Error messages dashboard
  dashboard/.env
  dashboard/__tests__/alertViewModelsTests.ts
  dashboard/__tests__/connectViewModelTests.ts
  dashboard/__tests__/notificationsTests.ts
  dashboard/__tests__/ordersViewModelsTests.ts
  dashboard/__tests__/waitersViewModelsTests.ts
  dashboard/src/context.ts
  dashboard/src/index.tsx
  dashboard/src/model/alertModel.ts
  dashboard/src/network/RequestsHandler.ts
  dashboard/src/network/api.ts
  dashboard/src/network/config.json
  dashboard/src/network/connectionHandler.ts
  dashboard/src/network/notifications.ts
  dashboard/src/typeGuard.ts
  dashboard/src/view/AppBarView.tsx
  dashboard/src/view/alert.tsx
  dashboard/src/view/alertView.tsx
  dashboard/src/viewController/ConnectViewController.tsx
  dashboard/src/viewController/OrdersViewController.tsx
  dashboard/src/viewController/StatusViewController.tsx
  dashboard/src/viewController/WaiterViewController.tsx
  dashboard/src/viewController/alertViewController.tsx
  dashboard/src/viewModel/alertViewModel.ts
  dashboard/src/viewModel/connectViewModel.ts
  dashboard/src/viewModel/ordersViewModel.ts
  dashboard/src/viewModel/waitersViewModel.ts
Labels: enhancement, testing

#178 PostgreSQL fix
  server/Data/entities/Domain/OrderDAO.ts
Labels: bug

#177 waiter api fix
  api.ts
  server/.env.example
Labels: documentation

#179 Production postgre sql configuration
  api.ts
  dashboard/__tests__/connectViewModelTests.ts
  dashboard/__tests__/notificationsTests.ts
  dashboard/__tests__/ordersViewModelsTests.ts
  dashboard/src/context.ts
  dashboard/src/network/api.ts
  dashboard/src/view/alertView.tsx
  dashboard/src/viewController/WaiterViewController.tsx
  dashboard/src/viewController/alertViewController.tsx
  server/Data/Stores/OrderStore.ts
  server/Data/entities/Domain/OrderDAO.ts
  server/Network/RequestHandler.ts
Labels: bug

#186 Refactoring dashboard
  dashboard/src/model/alertModel.ts
  dashboard/src/model/ordersModel.ts
  dashboard/src/network/RequestsHandler.ts
  dashboard/src/network/api.ts
  dashboard/src/network/connectionHandler.ts
  dashboard/src/view/ExpandCellGrid.tsx
  dashboard/src/view/alert.tsx
  dashboard/src/viewController/ConnectViewController.tsx
  dashboard/src/viewController/OrdersViewController.tsx
  dashboard/src/viewController/StatusViewController.tsx
  dashboard/src/viewController/WaiterViewController.tsx
  dashboard/src/viewModel/alertViewModel.ts
Labels: bug

#194 Encrypting passwords
  package-lock.json
  package.json
  server/Data/test_ResetDatabase.ts
  server/Logic/Authentication/Authenticator.ts
Labels: enhancement

#196 Fixed comapre function
  server/Logic/Authentication/Authenticator.ts
Labels: bug
