Repository RavidRo/service_anywhere, pull requests merged in 2022-04, with the labels that each got.

#75 Db and authentication
  .gitignore
  package-lock.json
  server/Data/AuthenticatorChecker.ts
  server/Data/GuestStore.ts
  server/Data/ItemStore.ts
  server/Data/OrderStore.ts
  server/Data/WaiterStore.ts
  server/Data/data-source.ts
  server/Data/entities/Authentication/UserCredentials.ts
  server/Data/entities/Domain/Guest.ts
  server/Data/entities/Domain/Item.ts
  server/Data/entities/Domain/Order.ts
  server/Data/entities/Domain/OrderToItem.ts
  server/Data/entities/Domain/Review.ts
  server/Data/entities/Domain/Worker.ts
  server/Data/index.ts
  server/Logic/Authentication/Authenticator.ts
  server/package.json
  server/tsconfig.json
Labels: enhancement, refactoring

#77 Removed the permission level parameter from login
  guests_app/src/View/MainPageView.tsx
  guests_app/src/ViewController/MainPageViewController.tsx
  package-lock.json
  server/Logic/Authentication/Authenticator.ts
  server/Network/RequestHandler.ts
  waiters_app/__tests__/TestsInterface/TestsConnect.tsx
Labels: refactoring

#91 tests
  dashboard/__tests__/notificationsTests.ts
  dashboard/__tests__/ordersViewModelsTests.ts
  dashboard/__tests__/waitersViewModelsTests.ts
  dashboard/babel.config.js
  dashboard/src/index.tsx
  dashboard/src/model/ordersModel.ts
  dashboard/src/model/waiterModel.ts
  dashboard/src/network/api.ts
  dashboard/src/network/connectionHandler.ts
  dashboard/src/network/notifications.ts
  dashboard/src/typeGuard.ts
  dashboard/src/view/ExpandCellGrid.tsx
  dashboard/src/viewController/StatusViewController.tsx
  dashboard/src/viewModel/ordersViewModel.ts
  dashboard/src/viewModel/waitersViewModel.ts
Labels: enhancement, testing

#93 Dashboard login
  dashboard/__tests__/connectViewModelTests.ts
  dashboard/__tests__/ordersViewModelsTests.ts
  dashboard/__tests__/waitersViewModelsTests.ts
  dashboard/src/index.tsx
  dashboard/src/model/ConnectModel.ts
  dashboard/src/model/ordersModel.ts
  dashboard/src/model/waiterModel.ts
  dashboard/src/network/RequestsHandler.ts
  dashboard/src/network/api.ts
  dashboard/src/network/connectionHandler.ts
  dashboard/src/typeGuard.ts
  dashboard/src/view/AppBarView.tsx
  dashboard/src/view/ExpandCellGrid.tsx
  dashboard/src/view/OrdersView.tsx
  dashboard/src/view/StatusView.tsx
  dashboard/src/view/WaiterDialogView.tsx
  dashboard/src/view/loginView.tsx
  dashboard/src/viewController/ConnectViewController.tsx
  dashboard/src/viewController/OrdersViewController.tsx
  dashboard/src/viewController/StatusViewController.tsx
  dashboard/src/viewModel/connectViewModel.ts
  dashboard/src/viewModel/ordersViewModel.ts
  dashboard/src/viewModel/waitersViewModel.ts
Labels: enhancement, testing
