Repository RavidRo/service_anywhere, pull requests merged in 2022-01, with the labels that each got.

#20 refactoring guest app
  clients/guests_app/App.tsx
  clients/guests_app/requests.ts
Labels: refactoring

#21 just checking tests run
  clients/guests_app/__tests__/App-test.tsx
  clients/guests_app/__tests__/location_tests.ts
Labels: testing

#22 Configured tests for react native project
  clients/waiters_app/__tests__/App-test.tsx
  clients/waiters_app/__tests__/Location-test.tsx
  clients/waiters_app/__tests__/Map-test.tsx
  clients/waiters_app/__tests__/Order-test.tsx
  clients/waiters_app/jest.config.js
  clients/waiters_app/src/networking/requests.ts
Labels: testing

#41 Dashboard refactor
  clients/dashboard/dashboard/package.json
  clients/dashboard/dashboard/src/App.js
  clients/dashboard/dashboard/src/config.json
  clients/dashboard/dashboard/src/index.css
  clients/dashboard/dashboard/src/index.js
  clients/dashboard/dashboard/src/network/api.js
  clients/dashboard/dashboard/src/network/config.json
  clients/dashboard/dashboard/src/setupTests.js
  clients/dashboard/dashboard/src/view/AppBarView.js
  clients/dashboard/dashboard/src/view/OrderView.js
  clients/dashboard/dashboard/src/view/WaiterDialogView.js
  clients/dashboard/dashboard/src/viewController/OrderViewController.js
  clients/dashboard/dashboard/src/viewController/OrdersViewController.js
  clients/dashboard/dashboard/src/viewController/WaiterDialogViewController.js
  clients/dashboard/dashboard/src/viewModel/ordersViewModel.js
  clients/dashboard/dashboard/src/viewModel/waitersViewModel.js
Labels: refactoring

#23 Fixed the bug
  clients/waiters_app/babel.config.js
  clients/waiters_app/metro.config.js
  clients/waiters_app/src/components/Orders.tsx
Labels: bug
